apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: assettemplates.hv.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: hv.com

  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: assettemplates
    # singular name to be used as an alias on the CLI and for display
    singular: assettemplate
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: AssetTemplate
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
      - at

  # either Namespaced or Cluster
  scope: Namespaced

  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                className:
                  type: string
                src:
                  type: string
            status:
              type: object
      subresources:
        status: {}
      additionalPrinterColumns:
      - name: Template Class
        type: string
        description: The asset template main class
        jsonPath: .spec.className
        priority: 0

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: assetinstances.hv.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: hv.com
  
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: assetinstances
    # singular name to be used as an alias on the CLI and for display
    singular: assetinstance
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: AssetInstance
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
      - ai

  # either Namespaced or Cluster
  scope: Namespaced

  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                template:
                  type: string
                args:
                  type: array
                  items:
                    x-kubernetes-int-or-string: true
                kwargs:
                  type: array
                  items:
                    x-kubernetes-preserve-unknown-fields: true
                    type: object
              required:
                - template
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              default:
                ray: 
                  created: false
                  generation: 0
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Template
          type: string
          description: The asset definition
          jsonPath: .spec.template
          priority: 0
        - name: Ray Status
          type: string
          description: Ray status
          jsonPath: .status.ray
          priority: 0

  